"""Supabase (PostgreSQL) store - the connection helper and the whole schema.

Everything the API used to keep in a local SQLite file now lives in Supabase:
  DATABASE_URL             the pooler connection string (Supabase Dashboard -> Connect ->
                           Pooler -> Transaction mode, port 6543), server only, never sent
                           to a browser.  SUPABASE_DB_URL is accepted as an alias.
  SUPABASE_PUBLISHABLE_KEY  browser-safe key; only usable because every table below has
                              Row Level Security enabled (see schema.sql)

Tables are created on first use (CREATE TABLE IF NOT EXISTS + indexes), so a brand new
Supabase project needs nothing but this file.  backend/schema.sql carries the same DDL
for the SQL editor.

Nothing here opens a connection at import time: db.py is imported by every module, so a
missing DATABASE_URL or a wrong password must never stop main.py from loading (on Vercel
that would turn into FUNCTION_INVOCATION_FAILED for every route).  The URL is validated
on the first query instead, raising DBError with the real reason, and /health answers
db: false while the database is unreachable.

The query code keeps SQLite's shape on purpose: `with db._connect() as c:` opens one
transaction, `?` placeholders are translated to Postgres `%s`, and rows answer both
`r["id"]` and `r[0]`.  Every statement is one command, prepared statements are disabled
(prepare_threshold=None) because Supabase's transaction pooler (port 6543) does not keep
them, and connections are kept short-lived (DB_POOL_MAX_LIFETIME seconds) so a serverless
instance never holds a stale session.
"""
import atexit
import os
import threading
import time
from contextlib import contextmanager
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from dotenv import load_dotenv

load_dotenv()                               # .env of whatever directory started the process
load_dotenv(Path(__file__).with_name(".env"))   # backend/.env, even when started elsewhere

import psycopg
from psycopg_pool import ConnectionPool


class DBError(RuntimeError):
    """Database misconfiguration or the database is unreachable. main.py answers 503 with
    this message; /health answers db:false. Never raised while importing this module."""


DB_URL = (os.environ.get("DATABASE_URL") or os.environ.get("SUPABASE_DB_URL") or "").strip()

# ---- schema: accounts, quotations, contacts, payments, and the LLM cache -----------------
TABLES = [
    """create table if not exists users (
         id            integer generated by default as identity primary key,
         name          text    not null default '',
         email         text    not null unique,
         phone         text    not null default '',
         password      text    not null,          -- 'pbkdf2_sha256$<iterations>$<salt>$<hash>'
         plan          text    not null default 'free',
         created_at    double precision not null,
         updated_at    double precision not null,
         last_login_at double precision
       )""",
    """create table if not exists quotations (
         id            text    primary key,
         user_email    text    not null,
         title         text    not null default '',
         host          text    not null default '',
         event_type    text    not null default 'Barat',
         event_date    text    not null default '',
         slot          text    not null default 'Evening',
         time          text    not null default '7:00 PM',
         guests        integer not null default 300,
         budget        integer not null default 1500000,
         menu_json     text    not null default '[]',
         services_json text    not null default '[]',
         notes         text    not null default '',
         pass_id       text    not null default 'free',
         status        text    not null default 'draft',
         created       double precision not null,
         updated       double precision not null,
         deleted       integer not null default 0
       )""",
    """create table if not exists quotation_halls (
         quotation_id       text not null,
         hall_id            text not null,
         whatsapp_clicked_at double precision,
         seq                bigint generated by default as identity,
         primary key (quotation_id, hall_id)
       )""",
    """create table if not exists contact_log (
         id            integer generated by default as identity primary key,
         user_email    text not null,
         quotation_id  text not null,
         hall_id       text not null,
         at            double precision not null
       )""",
    "create index if not exists ix_contact_user on contact_log (user_email, at)",
    "create index if not exists ix_contact_quote on contact_log (quotation_id)",
    """create table if not exists passes (
         id            integer generated by default as identity primary key,
         user_email    text not null,
         quotation_id  text not null,
         halls         integer not null,
         pkr           integer not null,
         status        text not null default 'paid',
         order_id      text not null,
         created       double precision not null
       )""",
    """create table if not exists payments (
         identifier    text    primary key,   -- PayPak identifier (<= 20 chars), also the order id
         user_email    text    not null,
         quotation_id  text    not null,
         pass_id       text    not null,
         pkr           integer not null,
         method        text    not null default '',
         status        text    not null default 'pending',  -- pending | success | failed | cancelled | expired
         tx_id         text    not null default '',
         created       double precision not null,
         updated       double precision not null
       )""",
    "create index if not exists ix_payments_user on payments (user_email, created)",
    # ---- LLM cache / daily call budget (backend/llm.py) ----
    "create table if not exists enrich (id text primary key, data text, ts double precision)",
    "create table if not exists llm_usage (day text primary key, calls integer)",
    """create table if not exists verified (
         city text not null, area text not null, section text not null,
         data text, ts double precision,
         primary key (city, area, section)
       )""",
    # RLS: the publishable key may sit in a browser, so nothing is readable through the
    # public REST API.  The backend connects as `postgres`, which bypasses RLS.
    "alter table users enable row level security",
    "alter table quotations enable row level security",
    "alter table quotation_halls enable row level security",
    "alter table contact_log enable row level security",
    "alter table passes enable row level security",
    "alter table payments enable row level security",
    "alter table enrich enable row level security",
    "alter table llm_usage enable row level security",
    "alter table verified enable row level security",
]


class Row(dict):
    """sqlite3.Row-shaped row: r["id"] and r[0] both read the same value, so query code
    written against SQLite keeps working unchanged."""

    __slots__ = ()

    def __getitem__(self, key):
        if isinstance(key, int):
            return list(dict.values(self))[key]
        return dict.__getitem__(self, key)


def _row_factory(cursor):
    if not cursor.description:          # DDL / INSERT ... RETURNING-less statements
        return lambda record: record
    names = [d.name for d in cursor.description]

    def build(record):
        row = Row()
        for name, value in zip(names, record):
            dict.__setitem__(row, name, value)
        return row

    return build


def _q(statement: str) -> str:
    """`?` placeholders -> Postgres `%s`.  No statement in this project uses a literal `?`."""
    return statement.replace("?", "%s")


def _connection_string() -> str:
    """DATABASE_URL, hardened for Supabase's pooler: sslmode=require when the URL does not
    say otherwise.  Raises DBError (only ever at call time, never at import) when the
    variable is missing."""
    if not DB_URL:
        raise DBError(
            "DATABASE_URL is not set. Add it in Vercel -> Settings -> Environment Variables "
            "(Supabase Dashboard -> Connect -> Pooler -> Transaction mode, port 6543). "
            "Locally, put it in backend/.env as DATABASE_URL or SUPABASE_DB_URL.")
    url = DB_URL.strip()
    if "://" in url:                       # postgresql://user:pass@host:6543/postgres?...
        parts = urlsplit(url)
        query = dict(parse_qsl(parts.query))
        query.setdefault("sslmode", "require")
        return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment))
    if "sslmode" not in url:               # keyword/value form: host=... port=6543 ...
        url += " sslmode=require"
    return url


def _probe(conninfo: str) -> None:
    """One short-lived connection with a clear reason on failure (wrong password, DNS,
    firewall, a pooler URL without the project ref in the username ...)."""
    try:
        with psycopg.connect(conninfo, connect_timeout=10, prepare_threshold=None) as c:
            with c.cursor() as cur:
                cur.execute("select 1")
                cur.fetchone()
    except Exception as x:
        raise DBError(f"Cannot connect to the database ({type(x).__name__}): {x}") from x


class Connection:
    """What every `with _connect() as c:` hands out: SQLite's execute(), Postgres underneath."""

    def __init__(self, raw):
        self._raw = raw

    def execute(self, statement, params=None):
        return self._raw.execute(_q(statement), params)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    @property
    def raw(self):
        return self._raw


_pool = None
_pool_lock = threading.Lock()
_schema_lock = threading.Lock()
_schema_done = False
_last_error = [None, 0.0]          # [message, when] - a dead database is re-probed at most every 5 s


def _get_pool():
    global _pool
    if _pool is None:
        with _pool_lock:
            if _pool is None:
                if _last_error[0] and time.time() - _last_error[1] < 5:
                    raise DBError(_last_error[0])
                conninfo = _connection_string()
                try:
                    _probe(conninfo)
                except DBError as x:
                    _last_error[0], _last_error[1] = str(x), time.time()
                    raise
                _last_error[0] = None
                _pool = ConnectionPool(
                    conninfo=conninfo,
                    min_size=int(os.environ.get("DB_POOL_MIN", "0")),
                    max_size=int(os.environ.get("DB_POOL_MAX", "3")),
                    max_lifetime=float(os.environ.get("DB_POOL_MAX_LIFETIME", "300")),
                    max_idle=60,
                    timeout=10,                       # how long a request waits for a connection
                    num_workers=1,                    # one thread is enough for a serverless process
                    kwargs={"row_factory": _row_factory,
                            "prepare_threshold": None,   # the transaction pooler drops prepared statements
                            "connect_timeout": 10},
                    open=True,
                )
    return _pool


def _close_pool():
    """Close the pool with the interpreter - psycopg_pool warns when a pool is only garbage
    collected after its worker thread has started shutting down."""
    global _pool
    with _pool_lock:
        pool, _pool = _pool, None
    if pool is not None:
        try:
            pool.close()
        except Exception:
            pass


atexit.register(_close_pool)


def ping() -> bool:
    """True when the database answers `select 1` right now. One short-lived connection,
    never raises - this is what /health reports as `db`."""
    try:
        with psycopg.connect(_connection_string(), connect_timeout=5, prepare_threshold=None) as c:
            with c.cursor() as cur:
                cur.execute("select 1")
                cur.fetchone()
        return True
    except Exception:
        return False


def ensure_schema(force: bool = False):
    """Create the tables once per process.  Safe to call from several threads."""
    global _schema_done
    if _schema_done and not force:
        return
    with _schema_lock:
        if _schema_done and not force:
            return
        pool = _get_pool()
        conn = pool.getconn()
        try:
            with conn.cursor() as cur:
                for statement in TABLES:
                    cur.execute(statement)
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            pool.putconn(conn)
        _schema_done = True


@contextmanager
def _connect():
    """One transaction.  Commits on the way out, rolls back on an error, always returns the
    connection to the pool - the same contract sqlite3's `with connection:` gave this code."""
    ensure_schema()
    pool = _get_pool()
    conn = pool.getconn()
    try:
        yield Connection(conn)
        conn.commit()
    except BaseException:
        try:
            conn.rollback()
        except Exception:
            conn.close()
        raise
    finally:
        pool.putconn(conn)


def unique_violation(exc: Exception) -> bool:
    """True when Postgres refused a row because a unique/primary key already exists."""
    return isinstance(exc, psycopg.errors.UniqueViolation)
