"""Supabase (PostgreSQL) store - the connection helper and the whole schema.

Everything the API used to keep in backend/users.sqlite now lives in Supabase:
  SUPABASE_DB_URL        the connection string, server only, never sent to a browser
  SUPABASE_PUBLISHABLE_KEY  browser-safe key; only usable because every table below has
                             Row Level Security enabled (see schema.sql)

Tables are created on first use (CREATE TABLE IF NOT EXISTS + indexes), so a brand new
Supabase project needs nothing but this file.  backend/schema.sql carries the same DDL
for the SQL editor.

The query code keeps SQLite's shape on purpose: `with db._connect() as c:` opens one
transaction, `?` placeholders are translated to Postgres `%s`, and rows answer both
`r["id"]` and `r[0]`.  Every statement is one command (the Supabase pooler runs in
transaction mode, where prepared statements and multi-command strings are refused).
"""
import atexit
import os
import threading
from contextlib import contextmanager
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()                               # .env of whatever directory started the process
load_dotenv(Path(__file__).with_name(".env"))   # backend/.env, even when started elsewhere

import psycopg
from psycopg_pool import ConnectionPool

DB_URL = (os.environ.get("SUPABASE_DB_URL") or os.environ.get("DATABASE_URL") or "").strip()
if not DB_URL:
    raise RuntimeError(
        "SUPABASE_DB_URL is not set. Copy backend/.env.example to backend/.env and put your "
        "Supabase connection string in it (Supabase Dashboard -> Connect -> Session pooler).")

# ---- schema: accounts, quotations, contacts, payments, and the LLM cache -----------------
TABLES = [
    """create table if not exists users (
         id            integer generated by default as identity primary key,
         name          text    not null default '',
         email         text    not null unique,
         phone         text    not null default '',
         password      text    not null,          -- 'pbkdf2_sha256$<iterations>$<salt>$<hash>'
         plan          text    not null default 'free',
         created_at    double precision not null,
         updated_at    double precision not null,
         last_login_at double precision
       )""",
    """create table if not exists quotations (
         id            text    primary key,
         user_email    text    not null,
         title         text    not null default '',
         host          text    not null default '',
         event_type    text    not null default 'Barat',
         event_date    text    not null default '',
         slot          text    not null default 'Evening',
         time          text    not null default '7:00 PM',
         guests        integer not null default 300,
         budget        integer not null default 1500000,
         menu_json     text    not null default '[]',
         services_json text    not null default '[]',
         notes         text    not null default '',
         pass_id       text    not null default 'free',
         status        text    not null default 'draft',
         created       double precision not null,
         updated       double precision not null,
         deleted       integer not null default 0
       )""",
    """create table if not exists quotation_halls (
         quotation_id       text not null,
         hall_id            text not null,
         whatsapp_clicked_at double precision,
         seq                bigint generated by default as identity,
         primary key (quotation_id, hall_id)
       )""",
    """create table if not exists contact_log (
         id            integer generated by default as identity primary key,
         user_email    text not null,
         quotation_id  text not null,
         hall_id       text not null,
         at            double precision not null
       )""",
    "create index if not exists ix_contact_user on contact_log (user_email, at)",
    "create index if not exists ix_contact_quote on contact_log (quotation_id)",
    """create table if not exists passes (
         id            integer generated by default as identity primary key,
         user_email    text not null,
         quotation_id  text not null,
         halls         integer not null,
         pkr           integer not null,
         status        text not null default 'paid',
         order_id      text not null,
         created       double precision not null
       )""",
    """create table if not exists payments (
         identifier    text    primary key,   -- PayPak identifier (<= 20 chars), also the order id
         user_email    text    not null,
         quotation_id  text    not null,
         pass_id       text    not null,
         pkr           integer not null,
         method        text    not null default '',
         status        text    not null default 'pending',  -- pending | success | failed | cancelled | expired
         tx_id         text    not null default '',
         created       double precision not null,
         updated       double precision not null
       )""",
    "create index if not exists ix_payments_user on payments (user_email, created)",
    # ---- LLM cache / daily call budget (backend/llm.py) ----
    "create table if not exists enrich (id text primary key, data text, ts double precision)",
    "create table if not exists llm_usage (day text primary key, calls integer)",
    """create table if not exists verified (
         city text not null, area text not null, section text not null,
         data text, ts double precision,
         primary key (city, area, section)
       )""",
    # RLS: the publishable key may sit in a browser, so nothing is readable through the
    # public REST API.  The backend connects as `postgres`, which bypasses RLS.
    "alter table users enable row level security",
    "alter table quotations enable row level security",
    "alter table quotation_halls enable row level security",
    "alter table contact_log enable row level security",
    "alter table passes enable row level security",
    "alter table payments enable row level security",
    "alter table enrich enable row level security",
    "alter table llm_usage enable row level security",
    "alter table verified enable row level security",
]


class Row(dict):
    """sqlite3.Row-shaped row: r["id"] and r[0] both read the same value, so query code
    written against SQLite keeps working unchanged."""

    __slots__ = ()

    def __getitem__(self, key):
        if isinstance(key, int):
            return list(dict.values(self))[key]
        return dict.__getitem__(self, key)


def _row_factory(cursor):
    if not cursor.description:          # DDL / INSERT ... RETURNING-less statements
        return lambda record: record
    names = [d.name for d in cursor.description]

    def build(record):
        row = Row()
        for name, value in zip(names, record):
            dict.__setitem__(row, name, value)
        return row

    return build


def _q(statement: str) -> str:
    """`?` placeholders -> Postgres `%s`.  No statement in this project uses a literal `?`."""
    return statement.replace("?", "%s")


class Connection:
    """What every `with _connect() as c:` hands out: SQLite's execute(), Postgres underneath."""

    def __init__(self, raw):
        self._raw = raw

    def execute(self, statement, params=None):
        return self._raw.execute(_q(statement), params)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    @property
    def raw(self):
        return self._raw


_pool = None
_pool_lock = threading.Lock()
_schema_lock = threading.Lock()
_schema_done = False


def _get_pool():
    global _pool
    if _pool is None:
        with _pool_lock:
            if _pool is None:
                _pool = ConnectionPool(
                    conninfo=DB_URL,
                    min_size=int(os.environ.get("DB_POOL_MIN", "1")),
                    max_size=int(os.environ.get("DB_POOL_MAX", "5")),
                    max_lifetime=1800,
                    max_idle=600,
                    num_workers=1,                       # one thread is enough for a dev process
                    kwargs={"row_factory": _row_factory,
                            "prepare_threshold": 0,      # the pooler serves transaction mode
                            "connect_timeout": 15},
                    open=True,
                )
    return _pool


def _close_pool():
    """Close the pool with the interpreter - psycopg_pool warns when a pool is only garbage
    collected after its worker thread has started shutting down."""
    global _pool
    with _pool_lock:
        pool, _pool = _pool, None
    if pool is not None:
        try:
            pool.close()
        except Exception:
            pass


atexit.register(_close_pool)


def ensure_schema(force: bool = False):
    """Create the tables once per process.  Safe to call from several threads."""
    global _schema_done
    if _schema_done and not force:
        return
    with _schema_lock:
        if _schema_done and not force:
            return
        pool = _get_pool()
        conn = pool.getconn()
        try:
            with conn.cursor() as cur:
                for statement in TABLES:
                    cur.execute(statement)
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            pool.putconn(conn)
        _schema_done = True


@contextmanager
def _connect():
    """One transaction.  Commits on the way out, rolls back on an error, always returns the
    connection to the pool - the same contract sqlite3's `with connection:` gave this code."""
    ensure_schema()
    pool = _get_pool()
    conn = pool.getconn()
    try:
        yield Connection(conn)
        conn.commit()
    except BaseException:
        try:
            conn.rollback()
        except Exception:
            conn.close()
        raise
    finally:
        pool.putconn(conn)


def unique_violation(exc: Exception) -> bool:
    """True when Postgres refused a row because a unique/primary key already exists."""
    return isinstance(exc, psycopg.errors.UniqueViolation)
