-- Shaadi Planner on Supabase - the whole schema.
--
-- backend/db.py runs exactly this on first boot (CREATE TABLE IF NOT EXISTS), so you only
-- need this file when you want to run it by hand in the Supabase SQL editor, or when you are
-- reviewing what lives where.
--
-- Every table has Row Level Security enabled with NO public policies: the publishable key may
-- sit in a browser, and through it PostgREST can reach nothing. The backend connects as the
-- `postgres` role (connection string in backend/.env), which bypasses RLS.

-- ------------------------------------------------------------------ accounts (users.py)
create table if not exists users (
  id            integer generated by default as identity primary key,
  name          text    not null default '',
  email         text    not null unique,
  phone         text    not null default '',
  password      text    not null,          -- 'pbkdf2_sha256$<iterations>$<salt>$<hash>'
  plan          text    not null default 'free',
  created_at    double precision not null,
  updated_at    double precision not null,
  last_login_at double precision
);

-- ------------------------------------------------------ quotations (quotations.py)
create table if not exists quotations (
  id            text    primary key,
  user_email    text    not null,
  title         text    not null default '',
  host          text    not null default '',
  event_type    text    not null default 'Barat',
  event_date    text    not null default '',
  slot          text    not null default 'Evening',
  time          text    not null default '7:00 PM',
  guests        integer not null default 300,
  budget        integer not null default 1500000,
  menu_json     text    not null default '[]',
  services_json text    not null default '[]',
  notes         text    not null default '',
  pass_id       text    not null default 'free',
  status        text    not null default 'draft',
  created       double precision not null,
  updated       double precision not null,
  deleted       integer not null default 0
);

create table if not exists quotation_halls (
  quotation_id        text not null,
  hall_id             text not null,
  whatsapp_clicked_at double precision,
  seq                 bigint generated by default as identity,
  primary key (quotation_id, hall_id)
);

create table if not exists contact_log (
  id           integer generated by default as identity primary key,
  user_email   text not null,
  quotation_id text not null,
  hall_id      text not null,
  at           double precision not null
);
create index if not exists ix_contact_user  on contact_log (user_email, at);
create index if not exists ix_contact_quote on contact_log (quotation_id);

create table if not exists passes (
  id           integer generated by default as identity primary key,
  user_email   text not null,
  quotation_id text not null,
  halls        integer not null,
  pkr          integer not null,
  status       text not null default 'paid',
  order_id     text not null,
  created      double precision not null
);

create table if not exists payments (
  identifier    text    primary key,   -- PayPak identifier (<= 20 chars), also the order id
  user_email    text    not null,
  quotation_id  text    not null,
  pass_id       text    not null,
  pkr           integer not null,
  method        text    not null default '',
  status        text    not null default 'pending',  -- pending | success | failed | cancelled | expired
  tx_id         text    not null default '',
  created       double precision not null,
  updated       double precision not null
);
create index if not exists ix_payments_user on payments (user_email, created);

-- ------------------------------------------------ LLM cache + daily budget (llm.py)
create table if not exists enrich (
  id   text primary key,
  data text,
  ts   double precision
);

create table if not exists llm_usage (
  day   text primary key,
  calls integer
);

create table if not exists verified (
  city    text not null,
  area    text not null,
  section text not null,
  data    text,
  ts      double precision,
  primary key (city, area, section)
);

-- ------------------------------------------------------------------------- RLS
alter table users           enable row level security;
alter table quotations      enable row level security;
alter table quotation_halls enable row level security;
alter table contact_log     enable row level security;
alter table passes          enable row level security;
alter table payments        enable row level security;
alter table enrich          enable row level security;
alter table llm_usage       enable row level security;
alter table verified        enable row level security;
-- No policies on purpose: nothing is allowed through the public REST API / publishable key.
-- Add per-row policies here if the browser ever needs to read its own data directly.
